Hdsrex 13
Sharecare/hds-submission-tools-ui pull request #24
Opened 2024-02-09 07:03 UTC by ushavemuganti-sharecare

https://arnoldmedia.jira.com/browse/HDSREX-13

### Developer checkboxes

- [ ] I have checked the base branch is correct and filled in the github milestone appropriately
- [ ] I have reviewed my PR to ensure I followed established coding standards
- [ ] I have linked any other PRs for this ticket if there are any
- [ ] I have verified that the code meets the requirements of the ticket
- [ ] I have verified that there are tests defined for QA in the JIRA ticket and or these changes are covered by
  regression

### Reviewer Checkboxes

- [ ] The milestone, base branch and JIRA release versions all match
- [ ] Understand the ticket requirements and ensure the changes meet these requirements
- [ ] Check the tests in the Jira ticket fully test the changes
- [ ] Check for coding standards
- [ ] Consider how this change may affect other pieces of the system - capture these effects in the JIRA ticket
- [ ] Consider any worst case scenarios for these code changes - compare this to the risk in JIRA and update if
  necessary

2024-02-12 11:33 UTC, Harshitha1238-sharecare commented
covered in another PR

2024-02-13 17:24 UTC, rajpeddalachugari requested changes

2024-02-13 17:24 UTC, rajpeddalachugari commented on src/index.html
> +        <link rel="stylesheet" href="https://unpkg.com/@progress/kendo-font-icons/dist/index.css" />
add it in angular.json

2024-02-13 17:24 UTC, rajpeddalachugari commented on src/app/patient-request-type-form/patient-request-type-form.component.ts
> +    // ];
remove commented code if not required.

2024-02-13 17:24 UTC, rajpeddalachugari commented on src/app/patient-request-type-form/patient-request-type-form.component.ts
> +export class PatientRequestTypeFormComponent {
implement onInit lifecycle hook to fix lint issues.

2024-02-13 17:24 UTC, rajpeddalachugari commented on src/app/patient-request-type-form/patient-request-type-form.component.ts
> +    public flipping: IconFlip[] = ['default', 'horizontal', 'vertical', 'both'];
do we need to flip icon ?

2024-02-13 17:24 UTC, rajpeddalachugari commented on src/app/patient-request-type-form/patient-request-type-form.component.html
> +                            flip="vertical"
flip attribute is added two times.

2024-02-14 04:46 UTC, ushavemuganti-sharecare commented on src/index.html
> +        <link rel="stylesheet" href="https://unpkg.com/@progress/kendo-font-icons/dist/index.css" />
removed the link from index.html and added input in anglar.json

2024-02-14 04:46 UTC, ushavemuganti-sharecare commented on src/app/patient-request-type-form/patient-request-type-form.component.ts
> +    // ];
removed the commented lines

2024-02-14 04:47 UTC, ushavemuganti-sharecare commented on src/app/patient-request-type-form/patient-request-type-form.component.ts
> +export class PatientRequestTypeFormComponent {
removed type any and implemented onInit lifecycle hook

2024-02-14 04:48 UTC, ushavemuganti-sharecare commented on src/app/patient-request-type-form/patient-request-type-form.component.ts
> +    public flipping: IconFlip[] = ['default', 'horizontal', 'vertical', 'both'];
added the flip default in html and removed the array from ts file

2024-02-14 04:48 UTC, ushavemuganti-sharecare commented on src/app/patient-request-type-form/patient-request-type-form.component.html
> +                            flip="vertical"
removed one flip attribute

2024-02-14 10:19 UTC, rajpeddalachugari approved these changes

2024-02-14 10:19 UTC, merged